# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    #TODO: Maybe add main package.json in root directory?
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install ./Wallet/
    - run: npm install -g pkg
    - run: pkg ./Wallet/
    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: wallet-linux
        # A file, directory or wildcard pattern that describes what to upload
        path: ./wallet-linux
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: wallet-windows
        # A file, directory or wildcard pattern that describes what to upload
        path: ./wallet-win.exe
    - name: Upload MacOS Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: wallet-maxos
        # A file, directory or wildcard pattern that describes what to upload
        path: ./wallet-macos
